### ISSUE TITLE
Maybe some instructions?

### ISSUE THREAD

**Issue by Rolandocmr** [kiritnarain/albiontrades#1]
Looks amazing! but don't know how to use it as a dumb person hahaha

**Comment by kiritnarain** [comment]
Hi Rolando, thanks for the feedback. I just published a live version of the site at https://albiontrades.kiritnarain.com/

**Comment by Rolandocmr** [comment]
Amazing job! thank you kindly!

**Comment by Rolandocmr** [comment]
I just did a few run test! worked amazingly for the time frame it has, putting the ("x" hour ago) really helps to get a reference of the risk. congratulations!

**Comment by kiritnarain** [comment]
Glad you're finding it helpful! I was able to make the 8.5m for premium in under a week using this! To enable more accurate prices, please download the Albion Data Client https://www.albion-online-data.com/

**Comment by Rolandocmr** [comment]
Im trying my best to get premium! i only have 3 days playing and hit my first 100k :) could i add you in game? I have downloaded THE ALBION ONLINE DATA PROJECT but im not yet sure how to use it.
